package adotego.view;

import adotego.controller.UsuarioController;
import adotego.modelos.Endereco;
import adotego.modelos.Tabela_usuarios;
import adotego.modelos.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Detalhe_usuario extends javax.swing.JFrame {
    
    private Usuario usuario;
    private final Tabela_usuarios tabela_usuarios_model;

    public Detalhe_usuario() {
        initComponents();
        label_aux.setVisible(false);
        tabela_usuarios_model = new Tabela_usuarios();
        jTable_usuarios.setModel(tabela_usuarios_model);
        this.setLocationRelativeTo(null);
        
        usuario = new Usuario();
        usuario.setEndereco(new Endereco());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jToolBar1 = new javax.swing.JToolBar();
        btn_salvar_usuario = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txtx_nascimento = new javax.swing.JTextField();
        txt_telefone_celular = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        txt_uf = new javax.swing.JTextField();
        txt_cep = new javax.swing.JTextField();
        txt_rua = new javax.swing.JTextField();
        txt_bairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        txt_id = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();
        btn_add_usuario = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        label_aux = new javax.swing.JLabel();
        txt_telefone_fixo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes ");
        setResizable(false);

        jInternalFrame1.setBackground(new java.awt.Color(245, 245, 255));
        jInternalFrame1.setVisible(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_salvar_usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_salvar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/plus.png"))); // NOI18N
        btn_salvar_usuario.setText("Salvar");
        btn_salvar_usuario.setFocusable(false);
        btn_salvar_usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salvar_usuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salvar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_usuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salvar_usuario);

        btn_excluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cross.png"))); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.setFocusable(false);
        btn_excluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_excluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_excluir);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/animal-paw-print.png"))); // NOI18N
        jButton3.setText("Nova Adoção");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/coins.png"))); // NOI18N
        jButton4.setText("Nova Doação");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jLabel1.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Data Nascimento");

        jLabel4.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Telefone-fixo");

        jLabel5.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Telefone-celular");

        jLabel6.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CPF");

        txt_nome.setText("Usuario teste");
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nomeFocusLost(evt);
            }
        });

        txt_email.setText("teste@hotmail.com");
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });

        txtx_nascimento.setText("05/01/1993");
        txtx_nascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtx_nascimentoFocusLost(evt);
            }
        });

        txt_telefone_celular.setText("4899103203");
        txt_telefone_celular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telefone_celularFocusLost(evt);
            }
        });

        txt_cpf.setText("32788623738");
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cpfFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Estado");

        jLabel9.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("CEP");

        jLabel10.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Rua");

        jLabel11.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Bairro");

        txt_cidade.setText("Florianopolis");
        txt_cidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cidadeFocusLost(evt);
            }
        });

        txt_uf.setText("santa catarina");
        txt_uf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ufFocusLost(evt);
            }
        });

        txt_cep.setText("88048416");
        txt_cep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cepFocusLost(evt);
            }
        });

        txt_rua.setText("r dos eucaliptos");
        txt_rua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ruaFocusLost(evt);
            }
        });

        txt_bairro.setText("campeche");
        txt_bairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bairroFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("N°");

        txt_numero.setText("32");
        txt_numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_numeroFocusLost(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_id.setText("ID:");

        jLabel12.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        jLabel12.setText("Configurações de usuario");

        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_usuarios);

        btn_add_usuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/left-arrow.png"))); // NOI18N
        btn_add_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_usuarioMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Usuarios Cadastrados");

        label_aux.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_aux.setForeground(new java.awt.Color(255, 51, 51));
        label_aux.setText(">");

        try {
            txt_telefone_fixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nome)
                                    .addComponent(txt_email)
                                    .addComponent(txtx_nascimento)
                                    .addComponent(txt_telefone_celular)
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(txt_telefone_fixo))
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(157, 157, 157))
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                                    .addComponent(txt_uf)
                                                    .addComponent(txt_cep)
                                                    .addComponent(txt_rua)
                                                    .addComponent(txt_bairro))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_add_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 117, Short.MAX_VALUE))))
                            .addComponent(txt_id)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(label_aux, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txt_id)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtx_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_telefone_fixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_add_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_telefone_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_aux)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
        Método responsável por recuperar o usuario selecionado na tabela, dae 
        preencher todos os inputs com o respectivo usuario.         
    */
    private void btn_add_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_usuarioMouseClicked
        
        int id_selected = tabela_usuarios_model
                //retorna -1 caso nao tenho nenhuma linha selecionada
                .getIdIntoTheRow(jTable_usuarios);
        
        if (id_selected != -1) {
            Usuario usuario = new UsuarioController()
                    .find(id_selected);
            this.build(usuario);
        }
        
    }//GEN-LAST:event_btn_add_usuarioMouseClicked

    /*
        Método responsável por salvar o objeto do tipo Usuario da tela em questão
        e salva-lo no banco de dados. Antes de salvar o objeto chamamos todos os
        metodos FocusLost para setarmos todas os propriedades novamente(desta 
        forma não é necessário apertar a tecla tab depois do ultimo campo de 
        texto
    */
    private void btn_salvar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_usuarioActionPerformed
        txt_bairroFocusLost(null);
        txt_cepFocusLost(null);
        txt_nomeFocusLost(null);        
        txt_telefone_celularFocusLost(null);
        txt_ufFocusLost(null);
        txt_telefone_fixoFocusLost(null);
        txtx_nascimentoFocusLost(null);
        txt_ruaFocusLost(null);
        txt_cidadeFocusLost(null);
        txt_numeroFocusLost(null);
        txt_emailFocusLost(null);
        txt_cpfFocusLost(null);
        
        if (true) {            
            new adotego.controller.UsuarioController().salvar(usuario);
            tabela_usuarios_model.atualizarTabela();
            this.reset_campos();
        } else {
            System.out.println("campos invalidos");
        }
    }//GEN-LAST:event_btn_salvar_usuarioActionPerformed

    /*
       Este método é invocado sempre que o txt_nome perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no campo_nome
    */
    private void txt_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusLost
        //se o campo nao for vazio 
        if (!txt_nome.getText().isEmpty()) {
            usuario.setNome(txt_nome.getText().trim());
        }
    }//GEN-LAST:event_txt_nomeFocusLost

     /*
       Este método é invocade sempre q o txt_nascimento perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no campo_txt_nascimento
    */
    private void txtx_nascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtx_nascimentoFocusLost
        try {
            //se o campo nao for vazio 
            if (!txtx_nascimento.getText().isEmpty()) {
                SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                Date date_parse = df.parse(txtx_nascimento.getText());
                Calendar cal = Calendar.getInstance();
                cal.setTime(date_parse);
                usuario.setData_nascimento(cal);
                
            }
        } catch (ParseException ex) {
            Logger.getLogger(Detalhe_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtx_nascimentoFocusLost
    /*
       Este método é invocade sempre q o txt_telefone_celular perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no campo txt_telefone_celular
    */
    private void txt_telefone_celularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telefone_celularFocusLost
        //se o campo nao for vazio 
        if (!txt_telefone_celular.getText().isEmpty()) {
            usuario.setTelefone_celular(txt_telefone_celular.getText());
        }        
    }//GEN-LAST:event_txt_telefone_celularFocusLost

    /*
       Este método é invocade sempre q o txt_cpf perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no campo_txt_cpf
    */
    private void txt_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusLost
        //se o campo nao for vazio 
        if (!txt_cpf.getText().isEmpty()) {
            usuario.setCpf(txt_cpf.getText());
        }
    }//GEN-LAST:event_txt_cpfFocusLost

    /*
       Este método é invocade sempre q o txt_cidade perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no txt_cidade
    */
    private void txt_cidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cidadeFocusLost
        //se o campo nao for vazio 
        if (!txt_cidade.getText().isEmpty()) {
            usuario.getEndereco().setCidade(txt_cidade.getText());
        }
    }//GEN-LAST:event_txt_cidadeFocusLost

    /*
       Este método é invocade sempre q o txt_uf perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no txt_uf
    */
    private void txt_ufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ufFocusLost
        //se o campo nao for vazio 
        if (!txt_uf.getText().isEmpty()) {
            usuario.getEndereco().setUf(txt_uf.getText());
        }
    }//GEN-LAST:event_txt_ufFocusLost

    /*
       Este método é invocade sempre q o txt_cep perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no txt_cep
    */
    private void txt_cepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cepFocusLost
        //se o campo nao for vazio 
        if (!txt_cep.getText().isEmpty()) {
            usuario.getEndereco().setCep(txt_cep.getText());
        }
    }//GEN-LAST:event_txt_cepFocusLost

    /*
       Este método é invocade sempre q o txt_rua perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no txt_rua
    */
    private void txt_ruaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ruaFocusLost
        //se o campo nao for vazio 
        if (!txt_rua.getText().isEmpty()) {
            usuario.getEndereco().setRua(txt_rua.getText());
        }
    }//GEN-LAST:event_txt_ruaFocusLost

    /*
       Este método é invocade sempre q o txt_numero perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no campo txt_numero
    */
    private void txt_numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_numeroFocusLost
        //se o campo nao for vazio 
        if (!txt_numero.getText().isEmpty()) {
            usuario.getEndereco().setNumero(Integer.parseInt(txt_numero.getText()));
        }
    }//GEN-LAST:event_txt_numeroFocusLost

    /*
       Este método é invocade sempre q o txt_bairro perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no campo_txt_bairro
    */
    private void txt_bairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bairroFocusLost
        //se o campo nao for vazio 
        if (!txt_bairro.getText().isEmpty()) {
            usuario.getEndereco().setBairro(txt_bairro.getText());
        }
    }//GEN-LAST:event_txt_bairroFocusLost
    
    /*
        Este método identifica qual usuario esta sendo utilizado para preencher
        os inputs e realiza a exclusão dele no banco de daodos.
    */
    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        if (usuario.getId() != null) {
            new UsuarioController().delete(usuario.getId());
        } else {
            label_aux.setText("Selecione um na tabela usuario para excluir");
            label_aux.setVisible(true);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed
    
    /*
       Este método é invocade sempre q o txt_email  perde o foco, e é responsável
       por setar no objeto usuario desta tela o valor que estiver no campo_txt_email
    */
    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        //se o campo nao for vazio
        if (!txt_email.getText().isEmpty()) {
            usuario.setEmail(txt_email.getText().trim());
        }
    }//GEN-LAST:event_txt_emailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detalhe_usuario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_usuario;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar_usuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_usuarios;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel label_aux;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JTextField txt_telefone_celular;
    private javax.swing.JFormattedTextField txt_telefone_fixo;
    private javax.swing.JTextField txt_uf;
    private javax.swing.JTextField txtx_nascimento;
    // End of variables declaration//GEN-END:variables

    //atribui o Usuario passado como parametro ao Usuario da variável local
    //e preenche todos os inputs com as propriedades deste usuario
    public void build(Usuario u) {
        usuario = u;
        preencher_campos();
    }
    //preenchar os campos do fomulario com os dados do usuario armazenado na 
    //variável local
    private void preencher_campos() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txt_id.setText(String
                .valueOf(txt_id.getText()
                        .concat(String.valueOf(usuario.getId()))));        
        txt_nome.setText(usuario.getNome());
        txt_telefone_fixo.setText(usuario.getEmail());
        txt_cpf.setText(usuario.getCpf());
        txt_telefone_fixo.setText(usuario.getTelefone_fixo());
        txt_telefone_celular.setText(usuario.getTelefone_celular());
        txtx_nascimento.setText(sdf.format(usuario.getData_nascimento().getTime()));
        txt_bairro.setText(usuario.getEndereco().getBairro());
        txt_cidade.setText(usuario.getEndereco().getCidade());
        txt_uf.setText(usuario.getEndereco().getUf());
        txt_cep.setText(usuario.getEndereco().getCep());
        txt_numero.setText(String.valueOf(usuario.getEndereco().getNumero()));
        txt_rua.setText(usuario.getEndereco().getRua());
        
        if (!this.isVisible()) {
            this.setVisible(true);
        }
    }

    //tornar todos os campos editáveis
    public void habilitar_campos_input() {
        txt_nome.setEditable(true);
        txt_telefone_fixo.setEditable(true);
        txt_cpf.setEditable(true);
        txt_telefone_fixo.setEditable(true);
        txt_telefone_celular.setEditable(true);
        txtx_nascimento.setEditable(true);
        txt_bairro.setEditable(true);
        txt_cidade.setEditable(true);
        txt_uf.setEditable(true);
        txt_cep.setEditable(true);
        txt_numero.setEditable(true);
        txt_rua.setEditable(true);
    }

    //tornar todos os campos do formulario não editavel
    public void desabilitar_campos_input() {
        txt_nome.setEditable(false);
        txt_telefone_fixo.setEditable(false);
        txt_cpf.setEditable(false);
        txt_telefone_fixo.setEditable(false);
        txt_telefone_celular.setEditable(false);
        txtx_nascimento.setEditable(false);
        txt_bairro.setEditable(false);
        txt_cidade.setEditable(false);
        txt_uf.setEditable(false);
        txt_cep.setEditable(false);
        txt_numero.setEditable(false);
        txt_rua.setEditable(false);
    }

    /*
        Este método retorna true se algum dos valores do formulários de 
        cadastro de usuarios estiver vazio
     */
    private boolean campos_preenchidos() {
        String mensagem = "Existem campos vazios";
        if (txt_nome.getText().isEmpty()
                || txt_telefone_fixo.getText().isEmpty()
                || txt_telefone_fixo.getText().isEmpty()
                || txt_telefone_celular.getText().isEmpty()
                || txtx_nascimento.getText().isEmpty()
                || txt_bairro.getText().isEmpty()
                || txt_cep.getText().isEmpty()
                || txt_uf.getText().isEmpty()
                || txt_cidade.getText().isEmpty()
                || txt_rua.getText().isEmpty()
                || txt_numero.getText().isEmpty()
                || txt_cpf.getText().isEmpty()) {
            
            if (!label_aux.getText().contains(mensagem)) {
                label_aux.setText(label_aux.getText()
                        .concat("\n" + mensagem));
                label_aux.setVisible(true);
                return false;
            } else {
                label_aux.getText().replace(mensagem, "");
            }            
        } else {
            return true;
        }
        return false;
    }    
    //preenche todo so inputs com uma String vazia, simulando estar vazias.
    public void reset_campos() {
        this.txt_nome.setText("");
        this.txt_telefone_fixo.setText("");
        this.txt_cpf.setText("");
        this.txtx_nascimento.setText("");
        this.txt_telefone_celular.setText("");
        this.txt_cidade.setText("");
        this.txt_telefone_fixo.setText("");
        this.txt_numero.setText("");
        this.txt_rua.setText("");
        this.txt_uf.setText("");
        this.txt_bairro.setText("");
        this.txt_cep.setText("");
    }
    
    /*
        Esté método é responsável por verificar se todos os campos estão devidamente
        preenchidos a nível de usuario.
    */
    private boolean validarCamposUsuario() {
        return campos_preenchidos() && validar_cpf() && validar_telefone_fixo()
                && validar_telefone_celular();
    }
    //vlaidação  CPF
    private boolean validar_cpf() {
        if (!(txt_cpf.getText().length() == 11)) {
            label_aux.setText(label_aux.getText().concat("\nCPF inválido"));
            return false;
        } else {
            char[] array = txt_cpf.getText().toCharArray();
            for (char d : array) {
                if (!Character.isDigit(d)) {
                    return false;
                }
            }
        }        
        
        return true;
        
    }
    //validar telefone fixo
    private boolean validar_telefone_fixo() {
        return txt_telefone_fixo.getText().length() == 8
                || txt_telefone_fixo.getText().length() == 12;
    }
    //validar telefone celular
    private boolean validar_telefone_celular() {
        return txt_telefone_celular.getText().length() == 8
                || txt_telefone_celular.getText().length() == 12;
    }
    
    private void txt_telefone_fixoFocusLost(Object object) {
        if (!txt_telefone_fixo.getText().isEmpty()) {
            usuario.setTelefone_fixo(txt_telefone_fixo.getText());
        }
        
    }
}
