/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adotego.view;

import adotego.controller.UsuarioController;
import adotego.modelos.Endereco;
import adotego.modelos.Tabela_usuarios;
import adotego.modelos.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author tmichelini
 */
public class Detalhe_usuario extends javax.swing.JFrame {

    private Usuario usuario;
    private final Tabela_usuarios tabela_usuarios_model ;
    
    /**
     * Creates new form Detalhe_usuario
     */
    public Detalhe_usuario() {
        initComponents();
        tabela_usuarios_model = new Tabela_usuarios();
        jTable_usuarios.setModel(tabela_usuarios_model);
        
        usuario = new Usuario();
        usuario.setEndereco(new Endereco());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jToolBar1 = new javax.swing.JToolBar();
        btn_salvar_usuario = new javax.swing.JButton();
        btn_toggle_editar = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txtx_nascimento = new javax.swing.JTextField();
        txt_telefone_fixo = new javax.swing.JTextField();
        txt_telefone_celular = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        txt_uf = new javax.swing.JTextField();
        txt_cep = new javax.swing.JTextField();
        txt_rua = new javax.swing.JTextField();
        txt_bairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        txt_id = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();
        btn_add_usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalhes ");
        setResizable(false);

        jInternalFrame1.setBackground(new java.awt.Color(245, 245, 255));
        jInternalFrame1.setVisible(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_salvar_usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_salvar_usuario.setIcon(new javax.swing.ImageIcon("/home/tmichelini/NetBeansProjects/adotego/src/icones/plus.png")); // NOI18N
        btn_salvar_usuario.setText("Salvar");
        btn_salvar_usuario.setFocusable(false);
        btn_salvar_usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salvar_usuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salvar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_usuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salvar_usuario);

        btn_toggle_editar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_toggle_editar.setIcon(new javax.swing.ImageIcon("/home/tmichelini/NetBeansProjects/adotego/src/icones/edit.png")); // NOI18N
        btn_toggle_editar.setText("Editar");
        btn_toggle_editar.setFocusable(false);
        btn_toggle_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_toggle_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_toggle_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toggle_editarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_toggle_editar);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/home/tmichelini/NetBeansProjects/adotego/src/icones/cross.png")); // NOI18N
        jButton2.setText("Excluir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("/home/tmichelini/NetBeansProjects/adotego/src/icones/animal-paw-print.png")); // NOI18N
        jButton3.setText("Nova Adoção");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("/home/tmichelini/NetBeansProjects/adotego/src/icones/coins.png")); // NOI18N
        jButton4.setText("Nova Doação");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jLabel1.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Data Nascimento");

        jLabel4.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Telefone-fixo");

        jLabel5.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Telefone-celular");

        jLabel6.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CPF");

        txt_nome.setEditable(false);
        txt_nome.setText("Tese");
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nomeFocusLost(evt);
            }
        });

        txt_email.setEditable(false);
        txt_email.setText("email@teste.com");
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });

        txtx_nascimento.setEditable(false);
        txtx_nascimento.setText("05/01/1993");
        txtx_nascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtx_nascimentoFocusLost(evt);
            }
        });

        txt_telefone_fixo.setEditable(false);
        txt_telefone_fixo.setText("48333278478");
        txt_telefone_fixo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telefone_fixoFocusLost(evt);
            }
        });

        txt_telefone_celular.setEditable(false);
        txt_telefone_celular.setText("48990393090");
        txt_telefone_celular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telefone_celularFocusLost(evt);
            }
        });

        txt_cpf.setEditable(false);
        txt_cpf.setText("3232090938203");
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cpfFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Estado");

        jLabel9.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("CEP");

        jLabel10.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Rua");

        jLabel11.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Bairro");

        txt_cidade.setEditable(false);
        txt_cidade.setText("floripa");
        txt_cidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cidadeFocusLost(evt);
            }
        });

        txt_uf.setEditable(false);
        txt_uf.setText("sc");
        txt_uf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ufFocusLost(evt);
            }
        });

        txt_cep.setEditable(false);
        txt_cep.setText("88048416");
        txt_cep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cepFocusLost(evt);
            }
        });

        txt_rua.setEditable(false);
        txt_rua.setText("rua das lameiras");
        txt_rua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ruaFocusLost(evt);
            }
        });

        txt_bairro.setEditable(false);
        txt_bairro.setText("campeche");
        txt_bairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bairroFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("N°");

        txt_numero.setEditable(false);
        txt_numero.setText("89");
        txt_numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_numeroFocusLost(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_id.setText("ID:");

        jLabel12.setFont(new java.awt.Font("Waree", 0, 18)); // NOI18N
        jLabel12.setText("Configurações de usuario");

        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_usuarios);

        btn_add_usuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_usuario.setIcon(new javax.swing.ImageIcon("/home/tmichelini/NetBeansProjects/adotego/src/icones/left-arrow.png")); // NOI18N
        btn_add_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_usuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nome)
                                    .addComponent(txt_email)
                                    .addComponent(txtx_nascimento)
                                    .addComponent(txt_telefone_fixo)
                                    .addComponent(txt_telefone_celular)
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(157, 157, 157))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                            .addComponent(txt_uf)
                                            .addComponent(txt_cep)
                                            .addComponent(txt_rua)
                                            .addComponent(txt_bairro))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(btn_add_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_id)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(28, 28, 28)
                        .addComponent(txt_id)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtx_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_telefone_fixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_add_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_telefone_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGap(18, 23, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_toggle_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toggle_editarActionPerformed
        if(btn_toggle_editar.isSelected()){
            habilitar_campos_input();        
        }else{
            desabilitar_campos_input();
        }
    }//GEN-LAST:event_btn_toggle_editarActionPerformed

    private void btn_add_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_usuarioMouseClicked
       
        int id_selected = tabela_usuarios_model
                                 .getIdIntoTheRow(jTable_usuarios);

        if(id_selected != -1){
            Usuario usuario = new UsuarioController()
                                             .find(id_selected);
            this.build(usuario);


        }
       
    }//GEN-LAST:event_btn_add_usuarioMouseClicked

    private void btn_salvar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_usuarioActionPerformed
        if(campos_validos())
            new adotego.controller.UsuarioController().salvar(usuario);
        tabela_usuarios_model.atualizarTabela();
        this.reset_campos();
    }//GEN-LAST:event_btn_salvar_usuarioActionPerformed

    private void txt_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusLost
        usuario.setNome(txt_nome.getText().trim());
    }//GEN-LAST:event_txt_nomeFocusLost

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        usuario.setEmail(txt_email.getText().trim());        
    }//GEN-LAST:event_txt_emailFocusLost

    private void txtx_nascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtx_nascimentoFocusLost
        try {
            SimpleDateFormat df =  new SimpleDateFormat("dd/MM/yyyy");
            Date date_parse = df.parse(txtx_nascimento.getText());
            Calendar cal =Calendar.getInstance();
            cal.setTime(date_parse);
            usuario.setData_nascimento(cal);
            System.out.println(df.format(usuario.getData_nascimento().getTime()));
            
        } catch (ParseException ex) {
            Logger.getLogger(Detalhe_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtx_nascimentoFocusLost

    private void txt_telefone_fixoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telefone_fixoFocusLost
        usuario.setTelefone_fixo(txt_telefone_fixo.getText());
    }//GEN-LAST:event_txt_telefone_fixoFocusLost

    private void txt_telefone_celularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telefone_celularFocusLost
        usuario.setTelefone_celular(txt_telefone_celular.getText());  
    }//GEN-LAST:event_txt_telefone_celularFocusLost

    private void txt_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusLost
        usuario.setCpf(txt_cpf.getText());
    }//GEN-LAST:event_txt_cpfFocusLost

    private void txt_cidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cidadeFocusLost
        usuario.getEndereco().setCidade(txt_cidade.getText());
    }//GEN-LAST:event_txt_cidadeFocusLost

    private void txt_ufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ufFocusLost
       usuario.getEndereco().setUf(txt_uf.getText());
    }//GEN-LAST:event_txt_ufFocusLost

    private void txt_cepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cepFocusLost
        usuario.getEndereco().setCep(txt_cep.getText());
    }//GEN-LAST:event_txt_cepFocusLost

    private void txt_ruaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ruaFocusLost
        usuario.getEndereco().setRua(txt_rua.getText());
    }//GEN-LAST:event_txt_ruaFocusLost

    private void txt_numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_numeroFocusLost
        usuario.getEndereco().setNumero(Integer.parseInt(txt_numero.getText()));
    }//GEN-LAST:event_txt_numeroFocusLost

    private void txt_bairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bairroFocusLost
        usuario.getEndereco().setBairro(txt_bairro.getText());
    }//GEN-LAST:event_txt_bairroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalhe_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detalhe_usuario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_usuario;
    private javax.swing.JButton btn_salvar_usuario;
    private javax.swing.JToggleButton btn_toggle_editar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_usuarios;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JTextField txt_telefone_celular;
    private javax.swing.JTextField txt_telefone_fixo;
    private javax.swing.JTextField txt_uf;
    private javax.swing.JTextField txtx_nascimento;
    // End of variables declaration//GEN-END:variables
    
    //atribui o Usuario passado como parametro ao Usuario da variável local
    public void build(Usuario u){
        usuario = u;
        preencher_campos();
    }
    //preenchar os campos do fomulario com os dados do usuario armazenado na 
        //variável local
    private void preencher_campos() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txt_id.setText(String
                .valueOf(txt_id.getText()
                       .concat(String.valueOf(usuario.getId()))));        
        txt_nome.setText(usuario.getNome());
        txt_email.setText(usuario.getEmail());
        txt_cpf.setText(usuario.getCpf());
        txt_telefone_fixo.setText(usuario.getTelefone_fixo());
        txt_telefone_celular.setText(usuario.getTelefone_celular());
        txtx_nascimento.setText(sdf.format(usuario.getData_nascimento().getTime()));
        txt_bairro.setText(usuario.getEndereco().getBairro());
        txt_cidade.setText(usuario.getEndereco().getCidade());
        txt_uf.setText(usuario.getEndereco().getUf());
        txt_cep.setText(usuario.getEndereco().getCep());
        txt_numero.setText(String.valueOf(usuario.getEndereco().getNumero()));
        txt_rua.setText(usuario.getEndereco().getRua());
        if(!this.isVisible())
            this.setVisible(true);
    }
    
    
    //tornar todos os campos editáveis
    public void habilitar_campos_input(){
        txt_nome.setEditable(true);
        txt_email.setEditable(true);
        txt_cpf.setEditable(true);
         txt_telefone_fixo.setEditable(true);
        txt_telefone_celular.setEditable(true);
        txtx_nascimento.setEditable(true);
        txt_bairro.setEditable(true);
        txt_cidade.setEditable(true);
        txt_uf.setEditable(true);
        txt_cep.setEditable(true);
        txt_numero.setEditable(true);
        txt_rua.setEditable(true);
    }
    //tornar todos os campos do formulario não editavel
    public void desabilitar_campos_input(){
    txt_nome.setEditable(false);
        txt_email.setEditable(false);
        txt_cpf.setEditable(false);
         txt_telefone_fixo.setEditable(false);
        txt_telefone_celular.setEditable(false);
        txtx_nascimento.setEditable(false);
        txt_bairro.setEditable(false);
        txt_cidade.setEditable(false);
        txt_uf.setEditable(false);
        txt_cep.setEditable(false);
        txt_numero.setEditable(false);
        txt_rua.setEditable(false);
    }
    
    /*
        Este método retorna true se algum dos valores do formulários de 
        cadastro de usuarios estiver vazio
    */
    private boolean campos_validos() {
        return !(txt_nome.getText() == null 
                    || txt_email.getText() == null
                    || txt_telefone_fixo.getText() == null 
                    || txt_telefone_celular.getText() == null
                    || txtx_nascimento.getText() == null
                    || txt_bairro.getText() == null
                    || txt_cep.getText() == null
                    || txt_uf.getText() == null
                    || txt_cidade.getText() == null
                    || txt_rua.getText() == null
                    || txt_numero.getText() == null
                    || txt_cpf.getText() ==null );
    }
    
    public void reset_campos(){
        this.txt_nome.setText("");
        this.txt_email.setText("");
        this.txt_cpf.setText("");
        this.txtx_nascimento.setText("");
        this.txt_telefone_celular.setText("");
        this.txt_telefone_fixo.setText("");
        this.txt_numero.setText("");
        this.txt_rua.setText("");
        this.txt_uf.setText("");
        this.txt_bairro.setText("");
        this.txt_cep.setText("");
    }
}
