/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adotego.view;

import adotego.modelos.Especie;
import adotego.modelos.Raca;
import adotego.util.FontHelper;
import adotego.util.Formatador;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author tmichelini
 */
public class NovoRelatorio extends javax.swing.JFrame {

    
    private Formatador formatador;
    private Especie especie;
    private String ambas = "Ambas";
    /**
     * Creates new form NovoRelatorio
     */
    public NovoRelatorio() {
        initComponents();
        especie = null;
        formatador = new Formatador();
        this.setTitle("Novo Relatório");
        initJComboEspecie();
        initJComboRaca();
        configurarFontes();
        configurar_icones();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabelEspecie = new javax.swing.JLabel();
        jComboBoxEspecie = new javax.swing.JComboBox<>();
        jComboBoxRaca = new javax.swing.JComboBox<>();
        jLabelEspecie1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jInternalFrame1.setVisible(true);

        jLabelEspecie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEspecie.setText("Especie:");

        jComboBoxEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEspecie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEspecieItemStateChanged(evt);
            }
        });

        jComboBoxRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelEspecie1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEspecie1.setText("Raça:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabelEspecie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspecie)
                    .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspecie1)
                    .addComponent(jComboBoxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEspecieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEspecieItemStateChanged
        
        
        if(jComboBoxEspecie.getSelectedIndex() > 0
               && !jComboBoxEspecie.getSelectedItem().toString().equals(ambas)){
           
            especie = new adotego.controller.EspecieController().getByName(jComboBoxEspecie.getSelectedItem().toString());
           atualizarJComboRaca();
        }else{
           especie=null;
           jComboBoxRaca.removeAllItems();
       } 
      
    }//GEN-LAST:event_jComboBoxEspecieItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxEspecie;
    private javax.swing.JComboBox<String> jComboBoxRaca;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelEspecie;
    private javax.swing.JLabel jLabelEspecie1;
    // End of variables declaration//GEN-END:variables

    private void configurarFontes() {
        FontHelper fh = new FontHelper();
        
        jLabelEspecie.setFont(fh.getLatoRegular(15f));
            jComboBoxEspecie.setFont(fh.getLatoRegular(15f));
    }
    
    private void configurar_icones() {
      ImageIcon icon = new ImageIcon("src/icones/Favicon.png");               
      this.setIconImage(icon.getImage());
    }

    private void initJComboEspecie() {
        
        jComboBoxEspecie.removeAllItems();
        
        List<Especie> especies = new adotego.controller.EspecieController().findAll();
        jComboBoxEspecie.addItem("");
        for (Especie especie : especies) {
            jComboBoxEspecie
                    .addItem(formatador
                            .formatarPrimeiraLetraMaiuscula(especie.getNome()));
        }
        jComboBoxEspecie.addItem(ambas);
    }

    private void initJComboRaca() {
       jComboBoxRaca.removeAllItems();   
    }
    
    public void atualizarJComboRaca(){
        if(especie != null){
            List<Raca> racas = new adotego.controller.RacaController().findRacaByEspecieName(especie.getNome());
            jComboBoxRaca.removeAllItems();
            for (Raca raca : racas) {
                jComboBoxRaca
                        .addItem(formatador
                                .formatarPrimeiraLetraMaiuscula(raca.getNome()));
            }
        }else{
            jComboBoxRaca.removeAllItems();
        }
        
        
    };
}
