
package adotego.view;

import adotego.controller.UsuarioController;
import adotego.modelos.Animal;
import adotego.modelos.Especie;
import adotego.modelos.Modelo_tabela_adocoes;
import adotego.modelos.Raca;
import adotego.modelos.Situacao;
import adotego.modelos.Tabela_Informacoes;
import adotego.modelos.Tabela_animais;
import adotego.modelos.Tabela_usuario_completa;
import adotego.modelos.Usuario;
import adotego.util.FontHelper;
import adotego.util.Formatador;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author tmichelini
 */
public final class PrincipalUI extends javax.swing.JFrame {
    
    private Tabela_usuario_completa model_tabela_usuarios_completa;
    private Tabela_animais model_tabela_animais;
    private Modelo_tabela_adocoes model_tabela_adocoes;
    private Tabela_Informacoes modelo_tabela_Informacoes;
    private final Formatador formatador;
    
    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        formatador = new Formatador();
        
       
        this.setTitle("Adotego");
        //abrir no centro da janela
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        init_jCombo_box_especie_pesquisa();
        init_jCombo_box_raca_pesquisa();
        init_jCombo_box_situacao(); 
        configurarInputPesquisa();
        iniciar_tabelas();
        
      
        configurarFontes();
        configurar_icones();
        
        
        
    }
    //fazendo teste para commitar @RodrigoStuani
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jTabbedPane_abas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame_informacoes = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_informacoes = new javax.swing.JTable();
        jButton_atualiza_informacoes = new javax.swing.JButton();
        jLabel_analiseDados = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_adocoes = new javax.swing.JTable();
        txt_total_doacoes = new javax.swing.JTextField();
        jLabelToTtalDoacoe = new javax.swing.JLabel();
        btn_atualizar_tabela_adocoes = new javax.swing.JButton();
        jLabel_titulo_adocoes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame_usuarios = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();
        btn_excluir_usuario = new javax.swing.JButton();
        btn_editar_usuario = new javax.swing.JButton();
        txt_pesquisar = new javax.swing.JTextField();
        jLabelPesquisaUsuarios = new javax.swing.JLabel();
        jCombo_box_opcoes_busca = new javax.swing.JComboBox<>();
        btn_novo_cadastro_usuario = new javax.swing.JButton();
        btn_atualiza_tabela_usuarios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jInternalFrame_animais = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_animais = new javax.swing.JTable();
        btn_editar_animal = new javax.swing.JButton();
        btn_excluir_animal = new javax.swing.JButton();
        btn_filtrar_animais = new javax.swing.JButton();
        jCombo_box_especie_pesquisa = new javax.swing.JComboBox<>();
        jCombo_box_raca_pesquisa = new javax.swing.JComboBox<>();
        jComboBox_situacao_pesquisa = new javax.swing.JComboBox<>();
        btn_novo_cadastro_animal = new javax.swing.JButton();
        jButton_atualiza_animal = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jMenuBar_menu = new javax.swing.JMenuBar();
        menuItemNovaRaca = new javax.swing.JMenu();
        jMenuItemNovoUsuario = new javax.swing.JMenuItem();
        jMenuItemNovaRaca = new javax.swing.JMenuItem();
        JMenuItemNovoUsuario = new javax.swing.JMenuItem();
        jMenuItem_novo_animal = new javax.swing.JMenuItem();
        jMenuItemNovaAdocao = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        menu_pesquisar = new javax.swing.JMenu();
        menu_relatorio = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane_abas.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane_abas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jInternalFrame_informacoes.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame_informacoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jInternalFrame_informacoes.setTitle("Informações");
        jInternalFrame_informacoes.setVisible(true);
        jInternalFrame_informacoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInternalFrame_informacoesFocusGained(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jTable_informacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable_informacoes);

        jButton_atualiza_informacoes.setBackground(new java.awt.Color(255, 255, 255));
        jButton_atualiza_informacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/refresh-page-option.png"))); // NOI18N
        jButton_atualiza_informacoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_atualiza_informacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualiza_informacoesActionPerformed(evt);
            }
        });

        jLabel_analiseDados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_analiseDados.setText("Análise de dados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_atualiza_informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jLabel_analiseDados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel_analiseDados, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_atualiza_informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(248, 248, 248));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jTable_adocoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_adocoes);

        jLabelToTtalDoacoe.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelToTtalDoacoe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelToTtalDoacoe.setText("Total em doações:");

        btn_atualizar_tabela_adocoes.setBackground(new java.awt.Color(255, 255, 255));
        btn_atualizar_tabela_adocoes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_atualizar_tabela_adocoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/refresh-page-option.png"))); // NOI18N
        btn_atualizar_tabela_adocoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_atualizar_tabela_adocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar_tabela_adocoesActionPerformed(evt);
            }
        });

        jLabel_titulo_adocoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo_adocoes.setText("Adoções Realizadas");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_atualizar_tabela_adocoes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelToTtalDoacoe, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_doacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jLabel_titulo_adocoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel_titulo_adocoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_total_doacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelToTtalDoacoe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_atualizar_tabela_adocoes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jInternalFrame_informacoesLayout = new javax.swing.GroupLayout(jInternalFrame_informacoes.getContentPane());
        jInternalFrame_informacoes.getContentPane().setLayout(jInternalFrame_informacoesLayout);
        jInternalFrame_informacoesLayout.setHorizontalGroup(
            jInternalFrame_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame_informacoesLayout.setVerticalGroup(
            jInternalFrame_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame_informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_informacoes)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_informacoes)
        );

        jTabbedPane_abas.addTab("Informações", jPanel2);

        jInternalFrame_usuarios.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame_usuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jInternalFrame_usuarios.setTitle("Controle de Usuarios");
        jInternalFrame_usuarios.setVisible(true);

        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_usuarios);

        btn_excluir_usuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir_usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_excluir_usuario.setText("Excluir");
        btn_excluir_usuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_excluir_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_usuarioActionPerformed(evt);
            }
        });

        btn_editar_usuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar_usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_editar_usuario.setText("Editar");
        btn_editar_usuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_editar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_usuarioActionPerformed(evt);
            }
        });

        txt_pesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabelPesquisaUsuarios.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelPesquisaUsuarios.setText("Pesquisar por ");

        jCombo_box_opcoes_busca.setBackground(new java.awt.Color(255, 255, 255));
        jCombo_box_opcoes_busca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCombo_box_opcoes_busca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF", "Email" }));

        btn_novo_cadastro_usuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo_cadastro_usuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_novo_cadastro_usuario.setText("Novo Cadastro");
        btn_novo_cadastro_usuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_novo_cadastro_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo_cadastro_usuarioActionPerformed(evt);
            }
        });

        btn_atualiza_tabela_usuarios.setBackground(new java.awt.Color(255, 255, 255));
        btn_atualiza_tabela_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/refresh-page-option.png"))); // NOI18N
        btn_atualiza_tabela_usuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_atualiza_tabela_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualiza_tabela_usuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame_usuariosLayout = new javax.swing.GroupLayout(jInternalFrame_usuarios.getContentPane());
        jInternalFrame_usuarios.getContentPane().setLayout(jInternalFrame_usuariosLayout);
        jInternalFrame_usuariosLayout.setHorizontalGroup(
            jInternalFrame_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_usuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jInternalFrame_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_usuariosLayout.createSequentialGroup()
                                .addComponent(jLabelPesquisaUsuarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCombo_box_opcoes_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_usuariosLayout.createSequentialGroup()
                                .addComponent(btn_atualiza_tabela_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_novo_cadastro_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_editar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jInternalFrame_usuariosLayout.setVerticalGroup(
            jInternalFrame_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_usuariosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_box_opcoes_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPesquisaUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_novo_cadastro_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btn_editar_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_atualiza_tabela_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_usuarios)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_usuarios)
        );

        jTabbedPane_abas.addTab("Usuarios", jPanel1);

        jInternalFrame_animais.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame_animais.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jInternalFrame_animais.setResizable(true);
        jInternalFrame_animais.setTitle("Controle de Animais");
        jInternalFrame_animais.setVisible(true);

        jTable_animais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable_animais);

        btn_editar_animal.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar_animal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_editar_animal.setText("Editar");
        btn_editar_animal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_editar_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_animalActionPerformed(evt);
            }
        });

        btn_excluir_animal.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir_animal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_excluir_animal.setText("Excluir");
        btn_excluir_animal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_excluir_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_animalActionPerformed(evt);
            }
        });

        btn_filtrar_animais.setBackground(new java.awt.Color(255, 255, 255));
        btn_filtrar_animais.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_filtrar_animais.setText("Filtrar");
        btn_filtrar_animais.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_filtrar_animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrar_animaisActionPerformed(evt);
            }
        });

        jCombo_box_especie_pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        jCombo_box_especie_pesquisa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCombo_box_especie_pesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_box_especie_pesquisaItemStateChanged(evt);
            }
        });

        jCombo_box_raca_pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        jCombo_box_raca_pesquisa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jComboBox_situacao_pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_situacao_pesquisa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        btn_novo_cadastro_animal.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo_cadastro_animal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_novo_cadastro_animal.setText("Novo Cadastro");
        btn_novo_cadastro_animal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_novo_cadastro_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo_cadastro_animalActionPerformed(evt);
            }
        });

        jButton_atualiza_animal.setBackground(new java.awt.Color(255, 255, 255));
        jButton_atualiza_animal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/refresh-page-option.png"))); // NOI18N
        jButton_atualiza_animal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_atualiza_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualiza_animalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame_animaisLayout = new javax.swing.GroupLayout(jInternalFrame_animais.getContentPane());
        jInternalFrame_animais.getContentPane().setLayout(jInternalFrame_animaisLayout);
        jInternalFrame_animaisLayout.setHorizontalGroup(
            jInternalFrame_animaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_animaisLayout.createSequentialGroup()
                .addGroup(jInternalFrame_animaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame_animaisLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_atualiza_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_novo_cadastro_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluir_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_editar_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_animaisLayout.createSequentialGroup()
                        .addGap(0, 541, Short.MAX_VALUE)
                        .addGroup(jInternalFrame_animaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_animaisLayout.createSequentialGroup()
                                .addComponent(jCombo_box_especie_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCombo_box_raca_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_situacao_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_filtrar_animais, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jInternalFrame_animaisLayout.setVerticalGroup(
            jInternalFrame_animaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_animaisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jInternalFrame_animaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_situacao_pesquisa)
                    .addComponent(jCombo_box_raca_pesquisa)
                    .addComponent(jCombo_box_especie_pesquisa)
                    .addComponent(btn_filtrar_animais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_animaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_novo_cadastro_animal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btn_excluir_animal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editar_animal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_atualiza_animal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_animais)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_animais, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane_abas.addTab("Animais", jPanel3);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane_abas.addTab("Controle de Doações", jTabbedPane2);

        jMenuBar_menu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        menuItemNovaRaca.setText("Arquivo");
        menuItemNovaRaca.setDelay(0);
        menuItemNovaRaca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        menuItemNovaRaca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menuItemNovaRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovaRacaActionPerformed(evt);
            }
        });

        jMenuItemNovoUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemNovoUsuario.setText("Nova Especie");
        jMenuItemNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoUsuarioActionPerformed(evt);
            }
        });
        menuItemNovaRaca.add(jMenuItemNovoUsuario);

        jMenuItemNovaRaca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemNovaRaca.setText("Nova Raça");
        jMenuItemNovaRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaRacaActionPerformed(evt);
            }
        });
        menuItemNovaRaca.add(jMenuItemNovaRaca);

        JMenuItemNovoUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JMenuItemNovoUsuario.setText("Novo Usuario");
        JMenuItemNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemNovoUsuarioActionPerformed(evt);
            }
        });
        menuItemNovaRaca.add(JMenuItemNovoUsuario);

        jMenuItem_novo_animal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem_novo_animal.setText("Novo Animal");
        jMenuItem_novo_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_novo_animalActionPerformed(evt);
            }
        });
        menuItemNovaRaca.add(jMenuItem_novo_animal);

        jMenuItemNovaAdocao.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemNovaAdocao.setText("Nova Adoção");
        jMenuItemNovaAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaAdocaoActionPerformed(evt);
            }
        });
        menuItemNovaRaca.add(jMenuItemNovaAdocao);

        jMenuItemSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        menuItemNovaRaca.add(jMenuItemSair);

        jMenuBar_menu.add(menuItemNovaRaca);

        menu_pesquisar.setText("Pesquisar");
        menu_pesquisar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuBar_menu.add(menu_pesquisar);

        menu_relatorio.setText("Relatório");
        menu_relatorio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuBar_menu.add(menu_relatorio);

        setJMenuBar(jMenuBar_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_abas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Este método é responsável por configurar as tabelas na PrincipaUI.class
    public void iniciar_tabelas() {
        /**
         * nova instância de um AbstractTableModel para configurar a tabela de
         * usuarios, e tabela animais
         */
        model_tabela_usuarios_completa = new Tabela_usuario_completa();
        model_tabela_animais = new Tabela_animais();
        model_tabela_adocoes =new Modelo_tabela_adocoes();
        modelo_tabela_Informacoes = new Tabela_Informacoes();
        
        //Setando o modelo criado acima nas tabelas
        jTable_usuarios.setModel(model_tabela_usuarios_completa);
        jTable_animais.setModel(model_tabela_animais);
        jTable_adocoes.setModel(model_tabela_adocoes);
        jTable_informacoes.setModel(modelo_tabela_Informacoes);
        configurar_tabela_usuarios();
        configurar_tabela_animais();
        configurar_tabela_adocoes();
        configurar_tabela_informacoes();
        atualizaTxtTotalDoacoes();
    }
    //evento lançado quando o botão Nova Especie no menu 'Arquivo' for clicado;
    //abre a janela de cadastro de Raca
    private void jMenuItemNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoUsuarioActionPerformed
        new Nova_especie().setVisible(true);
    }//GEN-LAST:event_jMenuItemNovoUsuarioActionPerformed
    
    //evento lançado quando o botão Nova Raca no menu 'Arquivo' for clicado;
    //abre a janela de cadastro de Raca
    private void jMenuItemNovaRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaRacaActionPerformed
        new Nova_raca().setVisible(true);
    }//GEN-LAST:event_jMenuItemNovaRacaActionPerformed
    
    //evento lançado quando o botão Nova Cadastro no menu 'Arquivo' for clicado
    //abre a janela de cadastro de usuarios;
    private void JMenuItemNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemNovoUsuarioActionPerformed
        new Detalhe_usuario().setVisible(true);
    }//GEN-LAST:event_JMenuItemNovoUsuarioActionPerformed
    
    //método chamado quando o item selecionado do JComboBox de especie para pesqusa
    // for chamado.
    private void jCombo_box_especie_pesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_box_especie_pesquisaItemStateChanged
        
        try {
            //se o item selecionado nao for o primeiro, pois o valor do primeiro
            //item é apenas uma título e não uma especie
            if (jCombo_box_especie_pesquisa.getSelectedIndex() != 0) {
                
                //recupera o item selecionado em String
                String especie_name_selected = String.valueOf(jCombo_box_especie_pesquisa
                        .getSelectedItem());
                //recupera uma lista baseada no nome da espeécie
                List<Raca> lista_raca = new adotego.controller.RacaController()
                        .findRacaByEspecieName(especie_name_selected);
                
                //como alteramos o jComboBox especie podemos atualizadar
                //o jComboBox de raças para a especie selecionada
                refresh_JCombo_box_raca_pesquisa(lista_raca);
                
            }else{
                refresh_JCombo_box_raca_pesquisa(null);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCombo_box_especie_pesquisaItemStateChanged
    
    /*
    Este método é chamado sempre que o botão de Filtrar animais for clicado
    e é responsável por filtrar a lista de animais que está na tabela de
    de acordo com os parametros selecionado dos JComboBoxEspecie, JComboBoxRaca,
    e no jComboBoxSituaçao
    */
    private void btn_filtrar_animaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrar_animaisActionPerformed
   
            //se todos os itens estiverem padrão preecnhe a tabela como todos os animais
             if(jCombo_box_especie_pesquisa.getSelectedIndex() == 0 
                     && jComboBox_situacao_pesquisa.getSelectedIndex() == 0
                     && jCombo_box_raca_pesquisa.getSelectedIndex() == 0)   {
                  
                 model_tabela_animais.atualizar_tabela();
             }else{
                //recupera lista de animais    
                List<Animal> animais_lista =  new adotego.controller.AnimalController().listarIdDesc();
                if(jCombo_box_especie_pesquisa.getSelectedIndex() > 0){
                //recupera o nome da especie selecionado
                String especie_name_selected = String.valueOf(jCombo_box_especie_pesquisa
                        .getSelectedItem());
                animais_lista = new adotego.controller.AnimalController() 
                          .findByEspecieName(especie_name_selected);
                          
                         //se estiver com a especie selecionada e com raca e situação no indice0
                       
                } 
                //remover os animais que possuir raca e situacao diferente da selecionada                
                Iterator<Animal> iterator = animais_lista.iterator();
                while (iterator.hasNext()) {
                    Animal animal = iterator.next();
                   
                    //se a raça selecionada for for diferente da raças
                    //selecionada anteriormente, excluímos da lista
                    if(jCombo_box_raca_pesquisa.getSelectedIndex() > 0){
                        String raca = String.valueOf(jCombo_box_raca_pesquisa.getSelectedItem());
                        if ((!animal.getRaca().getNome().equalsIgnoreCase(raca))) {
                            iterator.remove();
                        }
                    }
                    
                    if (jComboBox_situacao_pesquisa.getSelectedIndex() > 0 ){                        
                        String situacao = String.valueOf(jComboBox_situacao_pesquisa.getSelectedItem());
                        if (!animal.getSituacao().getDescricao().equalsIgnoreCase(situacao)) {
                            iterator.remove();
                        }                    
                }
                         
                }
                model_tabela_animais.atualizar_tabela(animais_lista);
             }
    }//GEN-LAST:event_btn_filtrar_animaisActionPerformed
    /*
    Este método é executado quando o botão de excluir animal for selecionado
    ele basicamente recupera o id selecionado na tabela e exclui o animal
    correspondente no banco de dados
    */
    private void btn_excluir_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_animalActionPerformed
        //recupera id
        int[] ids = model_tabela_animais.getIdsIntoTheRow(jTable_animais);
        //apaga o usuario correspondente
        for (int id : ids) {
            if(!new adotego.controller.AnimalController().delete(id)){
               Object[] options = { "Ok", "Cancelar" };
               
               JOptionPane.showOptionDialog(null, "O Animal de ID:"+id+
                       " está relacionado a uma adoção, portanto é impossível "
                       + "exclui-lo", "Aviso", JOptionPane.DEFAULT_OPTION, 
                       JOptionPane.OK_OPTION, null, options, options[0]);
            }
        }
        model_tabela_animais.atualizar_tabela();
        
    }//GEN-LAST:event_btn_excluir_animalActionPerformed
    
    /*
    Este método é executado quando o botão editar animal for clicado, ele
    basicamente recupera o id selecionado e abre a janela para edição de
    animais com os campos de inputs já preenchidos para edição
    */
    private void btn_editar_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_animalActionPerformed
        int id_animal_selected = model_tabela_animais.getSelectedIndex(jTable_animais);
        Animal animal = model_tabela_animais.getAnimalByIndex(id_animal_selected);
        new Detalhe_animal().build(animal);
    }//GEN-LAST:event_btn_editar_animalActionPerformed
    /*
    Este método é executado quando o botão editar usuario for clicado, ele
    basicamente recupera o id selecionado e abre a janela para edição de
    usuarios com os campos de inputs já preenchidos para edição
    */
    private void btn_editar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_usuarioActionPerformed
        int id_select = model_tabela_usuarios_completa.getIdIntoTheRow(jTable_usuarios);
        Usuario u = new adotego.controller.UsuarioController().find(id_select);
        new Detalhe_usuario().build(u);
    }//GEN-LAST:event_btn_editar_usuarioActionPerformed
    
    /*
    Este método é executado quando o botão de excluir usuario for selecionado
    ele basicamente recupera o id selecionado na tabela e exclui o usuario
    correspondente no banco de dados
    */
    private void btn_excluir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_usuarioActionPerformed
        
        int[] ids_selecionados = model_tabela_usuarios_completa.getIdsIntoTheRow(jTable_usuarios);      
        UsuarioController uc = new adotego.controller.UsuarioController();
        for (int i : ids_selecionados) {
            uc.delete(i);
        }
        model_tabela_usuarios_completa.atualizarTabela();
        
    }//GEN-LAST:event_btn_excluir_usuarioActionPerformed
    /*
    Este método identifica um duplo clique em algum usuario da tabela e
    abre a janela correspondete para edição, já com os campos inputs preeenchidos
    */
    private void jTable_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_usuariosMouseClicked
        if (evt.getClickCount() == 2) {
            int id_clicado = model_tabela_usuarios_completa.getIdIntoTheRow(jTable_usuarios);
            Usuario usuario = new adotego.controller.UsuarioController().find(id_clicado);
            new Detalhe_usuario().build(usuario);
        }
    }//GEN-LAST:event_jTable_usuariosMouseClicked

   //este método abre a janela para cadastro de um novo animal
    private void jMenuItem_novo_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_novo_animalActionPerformed
        new Detalhe_animal().setVisible(true);
    }//GEN-LAST:event_jMenuItem_novo_animalActionPerformed
    //este método abre a janela para cadastro de um novo animal
    private void btn_novo_cadastro_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo_cadastro_animalActionPerformed
        new Detalhe_animal().setVisible(true);
    }//GEN-LAST:event_btn_novo_cadastro_animalActionPerformed
    
    private void menuItemNovaRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovaRacaActionPerformed
                new Nova_Adocao().setVisible(true);
    }//GEN-LAST:event_menuItemNovaRacaActionPerformed
    
    private void jMenuItemNovaAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaAdocaoActionPerformed
        new Nova_Adocao().setVisible(true);
    }//GEN-LAST:event_jMenuItemNovaAdocaoActionPerformed
    
    private void jInternalFrame_informacoesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInternalFrame_informacoesFocusGained
        model_tabela_adocoes.atualiza();
        
    }//GEN-LAST:event_jInternalFrame_informacoesFocusGained
    
    private void btn_atualizar_tabela_adocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar_tabela_adocoesActionPerformed
        model_tabela_adocoes.atualiza();
        txt_total_doacoes.setText("");
        txt_total_doacoes.setText("R$:"+String
                .valueOf(model_tabela_adocoes.getTotal_doacoes()));
      
    }//GEN-LAST:event_btn_atualizar_tabela_adocoesActionPerformed
    
    private void btn_atualiza_tabela_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualiza_tabela_usuariosActionPerformed
        model_tabela_usuarios_completa.atualizarTabela();
    }//GEN-LAST:event_btn_atualiza_tabela_usuariosActionPerformed

    private void btn_novo_cadastro_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo_cadastro_usuarioActionPerformed
        new Detalhe_usuario().setVisible(true);
    }//GEN-LAST:event_btn_novo_cadastro_usuarioActionPerformed

    private void jButton_atualiza_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualiza_animalActionPerformed
        model_tabela_animais.atualizar_tabela();
    }//GEN-LAST:event_jButton_atualiza_animalActionPerformed

    private void jButton_atualiza_informacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualiza_informacoesActionPerformed
        atualizar_tabela_informacoes();
    }//GEN-LAST:event_jButton_atualiza_informacoesActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemNovoUsuario;
    private javax.swing.JButton btn_atualiza_tabela_usuarios;
    private javax.swing.JButton btn_atualizar_tabela_adocoes;
    private javax.swing.JButton btn_editar_animal;
    private javax.swing.JButton btn_editar_usuario;
    private javax.swing.JButton btn_excluir_animal;
    private javax.swing.JButton btn_excluir_usuario;
    private javax.swing.JButton btn_filtrar_animais;
    private javax.swing.JButton btn_novo_cadastro_animal;
    private javax.swing.JButton btn_novo_cadastro_usuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_atualiza_animal;
    private javax.swing.JButton jButton_atualiza_informacoes;
    private javax.swing.JComboBox<String> jComboBox_situacao_pesquisa;
    private javax.swing.JComboBox<String> jCombo_box_especie_pesquisa;
    private javax.swing.JComboBox<String> jCombo_box_opcoes_busca;
    private javax.swing.JComboBox<String> jCombo_box_raca_pesquisa;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame_animais;
    private javax.swing.JInternalFrame jInternalFrame_informacoes;
    private javax.swing.JInternalFrame jInternalFrame_usuarios;
    private javax.swing.JLabel jLabelPesquisaUsuarios;
    private javax.swing.JLabel jLabelToTtalDoacoe;
    private javax.swing.JLabel jLabel_analiseDados;
    private javax.swing.JLabel jLabel_titulo_adocoes;
    private javax.swing.JMenuBar jMenuBar_menu;
    private javax.swing.JMenuItem jMenuItemNovaAdocao;
    private javax.swing.JMenuItem jMenuItemNovaRaca;
    private javax.swing.JMenuItem jMenuItemNovoUsuario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItem_novo_animal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane_abas;
    private javax.swing.JTable jTable_adocoes;
    private javax.swing.JTable jTable_animais;
    private javax.swing.JTable jTable_informacoes;
    private javax.swing.JTable jTable_usuarios;
    private javax.swing.JMenu menuItemNovaRaca;
    private javax.swing.JMenu menu_pesquisar;
    private javax.swing.JMenu menu_relatorio;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_total_doacoes;
    // End of variables declaration//GEN-END:variables
    
    //inicializa o jCombo de especia de acordo com toas as especies
    // no banco de dados
    private void init_jCombo_box_especie_pesquisa()  {
        List<Especie> especies = new adotego.controller.EspecieController().findAll();
        jCombo_box_especie_pesquisa.addItem("Especie");
        for (Especie especie : especies) {
            jCombo_box_especie_pesquisa.addItem(
                    formatador.formatarPrimeiraLetraMaiuscula(especie.getNome()));
        }
    }
    //atualiza o jCombo de raças para de acordo com a especie selecionada
    private void refresh_JCombo_box_raca_pesquisa(List<Raca> lista) {
        
        if(lista == null ){
            init_jCombo_box_raca_pesquisa();
        }else{
            jCombo_box_raca_pesquisa.removeAllItems();
            jCombo_box_raca_pesquisa.addItem("Raça");
            lista.stream().forEach((raca) -> {
                jCombo_box_raca_pesquisa.addItem(raca.getNome());
            });
        }
    }
    /*
    O Jcombo de raças necessita que o Jcombo de especie esteja com algums item
    selecionado, antes preenchemos apenas com o titulo
    */
    private void init_jCombo_box_raca_pesquisa() {
        jCombo_box_raca_pesquisa.removeAllItems();
        jCombo_box_raca_pesquisa.addItem("Raça");
    }
    
    /*
    Este método é responsável por configuras os tamanhos da colunas da tabela
    usuario
    */
    private void configurar_tabela_usuarios() {
        jTable_usuarios.setRowHeight(26);
        
        int columnCount = jTable_usuarios.getColumnCount();
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
            dtcr.setHorizontalAlignment(SwingConstants.CENTER);
         
        int width = jTable_usuarios.getWidth();
        for (int i = 0; i < columnCount; i++) {
            TableColumn column = jTable_usuarios.getColumnModel().getColumn(i);            
            column.setCellRenderer(dtcr);
            
            switch (i) {
                case 0:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.03))));
                    break;
                case 1:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.15))));
                    break;
                case 2:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.25))));
                    break;
                case 3:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.18))));
                    break;
                case 4:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.15))));
                    break;
                case 5:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.15))));
                    break;
                case 6:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.09))));
                    
            }
            
        }
    }
    
    //preenche o jCombo_situação de acordo com todos os registros da tabela
    //especie no banco de dados
    private void init_jCombo_box_situacao() {
        List<Situacao> situacoes = new adotego.controller.SituacaoController().findAll();
        jComboBox_situacao_pesquisa.addItem("Situação");
        for (Situacao sit : situacoes) {
            jComboBox_situacao_pesquisa
                    .addItem(formatador
                            .formatarPrimeiraLetraMaiuscula(sit.getDescricao()));
        }
        
    }
    
    //atualiza o input com o total de doações atualizado
    public void atualizaTxtTotalDoacoes(){
        txt_total_doacoes.setText("");
        txt_total_doacoes.setText("R$:"+model_tabela_adocoes.getTotal_doacoes());
    }
    
    /*
        Método responsável por configurar os tamanho da colunas na tabela de animais
    */
    private void configurar_tabela_animais() {
         jTable_animais.setRowHeight(26);
        int columnCount = jTable_animais.getColumnCount();
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
            dtcr.setHorizontalAlignment(SwingConstants.CENTER);
          
        int width = jTable_animais.getWidth();
        for (int i = 0; i < columnCount; i++) {
            TableColumn column = jTable_animais.getColumnModel().getColumn(i);
            column.setCellRenderer(dtcr);  
            switch (i) {
                case 0:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.05))));
                    break;
                case 1:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.20))));
                    break;
                case 2:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.15))));
                    break;
                case 3:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.30))));
                    break;
                case 4:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.30))));
                    
            }
            
        }
    }
    
   

    /*
    Configura o tamanho das colunas da tabela_doações
    */
    private void configurar_tabela_adocoes() {
        int columnCount = jTable_adocoes.getColumnCount();         
        DefaultTableCellRenderer dtcr;
        
        jTable_adocoes.setRowHeight(26);
        int width = jTable_adocoes.getWidth();
        for (int i = 0; i < columnCount; i++) {
            TableColumn column = jTable_adocoes.getColumnModel().getColumn(i);
            dtcr = new DefaultTableCellRenderer();
            switch (i) {
                
                case 0:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.10))));
                    dtcr.setHorizontalAlignment(SwingConstants.CENTER);
                    column.setCellRenderer(dtcr);
                    break;
                case 1:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.35))));
                    dtcr.setHorizontalAlignment(SwingConstants.CENTER);
                    column.setCellRenderer(dtcr);
                    break;
                case 2:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.15))));
                    dtcr.setHorizontalAlignment(SwingConstants.CENTER);
                    column.setCellRenderer(dtcr);
                    break;
                case 3:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.30))));
                    dtcr.setHorizontalAlignment(SwingConstants.CENTER);
                    column.setCellRenderer(dtcr);
                    break;
                case 4:
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.10))));
                    dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
                    column.setCellRenderer(dtcr);
                    
            }
            
        }
    }

    private void configurar_tabela_informacoes() {
      
        modelo_tabela_Informacoes.atualizar();
        
        
        int columnCount = jTable_informacoes.getColumnCount();         
        DefaultTableCellRenderer dtcr;
        
        jTable_informacoes.setRowHeight(26);
        int width = jTable_informacoes.getWidth();
        for (int i = 0; i < columnCount; i++) {
            TableColumn column = jTable_informacoes.getColumnModel().getColumn(i);
            dtcr = new DefaultTableCellRenderer();
            switch (i) {
                case 0:{
                    dtcr.setHorizontalAlignment(SwingConstants.CENTER);
                    column.setCellRenderer(dtcr);
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.90))));
                    
                }break;
                case 1:{
                    dtcr.setHorizontalAlignment(SwingConstants.CENTER);
                    column.setCellRenderer(dtcr);
                    column.setPreferredWidth(Integer
                            .parseInt(String.valueOf(Math.round(width*0.10))));
                    
                }break;    
                    
            }
            
        }
    }

    private void atualizar_tabela_informacoes() {
       modelo_tabela_Informacoes.atualizar();
    }

    //este método é chamado a casa alteração do texto do input_pesquisa de Usuarios.  
    private void configurarInputPesquisa() {
        txt_pesquisar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                doo();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                doo();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                doo();
            }
            
            private void doo() {
                 // recupera uma String que está selecionado no jCombo_box_opcoes_busca
                // para que seja utilizado como parametro no filtro, retira os espaços,
                // etransforma tudo em letras minúsculas
                String parametro = String.valueOf(jCombo_box_opcoes_busca.getSelectedItem())
                        .toLowerCase()
                        .trim();

                //recupera o texto digitado pelo usuario para utilizarmos na pesquisa no
                //banco de dados
                String str_pesquisa = txt_pesquisar.getText().trim();

                //se o campo de pesquisa não estiver preenchido a tabela é atualizada
                //com todos os dados do banco
                if (str_pesquisa.isEmpty()) {
                    model_tabela_usuarios_completa.atualizarTabela();
                } else {
                    /*
                    switch para identificar qual parametro está selecionado no
                    jCombo_box_opcoes_busca e utiliza-lo como parametro para filtrar
                    os resultados da tabela,
                    Ex: se o campo nome estiver selecionado pesquisamos as ocorrencias
                    do valor no campo input para filtrar os resultados
                    */
                    switch (parametro) {
                        case "nome":
                            model_tabela_usuarios_completa
                                    .setList(new UsuarioController()
                                            .findLikeName(str_pesquisa));
                            break;
                        case "cpf":
                            model_tabela_usuarios_completa
                                    .setList(new UsuarioController()
                                            .findLikeCpf(str_pesquisa));
                            break;
                        case "email":
                            model_tabela_usuarios_completa
                                    .setList(new UsuarioController()
                                            .findLikeEmail(str_pesquisa));
                            break;

                        default:
                            model_tabela_usuarios_completa.atualizarTabela();
                    }
                }
        
            }
           
        });
         
    }

    private void configurarFontes() {
        FontHelper fh = new FontHelper();
        
       jInternalFrame_animais.getComponent(WIDTH).setFont(fh.getLatoBold(17f));
       jInternalFrame_informacoes.getComponent(WIDTH).setFont(fh.getLatoBold(17f));
       jInternalFrame_usuarios.getComponent(WIDTH).setFont(fh.getLatoBold(17f));
       jTabbedPane_abas.setFont(fh.getLatoRegular(14f));
      
       menuItemNovaRaca.setFont(fh.getLatoBold(15f));     
       menu_pesquisar.setFont(fh.getLatoBold(15f));
       menu_relatorio.setFont(fh.getLatoBold(15f));
       
       jMenuItemNovaRaca.setFont(fh.getLatoBold(15f));
       jMenuItemNovaAdocao.setFont(fh.getLatoBold(15f));
       jMenuItemNovoUsuario.setFont(fh.getLatoBold(15f));
       jMenuItemSair.setFont(fh.getLatoBold(15f));
       jMenuItem_novo_animal.setFont(fh.getLatoBold(15f));
       
       
       jTable_adocoes.setFont(fh.getLatoLight(16f));
       jTable_animais.setFont(fh.getLatoLight(16f));
       jTable_informacoes.setFont(fh.getLatoLight(16f));
       jTable_usuarios.setFont(fh.getLatoLight(16f));
       
       
       btn_novo_cadastro_usuario.setFont(fh.getLatoBold(17f));
       btn_excluir_animal.setFont(fh.getLatoBold(17f));
       btn_excluir_usuario.setFont(fh.getLatoBold(17f));
       btn_editar_animal.setFont(fh.getLatoBold(17f));
       btn_editar_usuario.setFont(fh.getLatoBold(17f));
       btn_filtrar_animais.setFont(fh.getLatoBold(17f));
       btn_novo_cadastro_animal.setFont(fh.getLatoBold(17f));
       
       jCombo_box_especie_pesquisa.setFont(fh.getLatoRegular(15f));
       jCombo_box_opcoes_busca.setFont(fh.getLatoRegular(15f));
       jCombo_box_raca_pesquisa.setFont(fh.getLatoRegular(15f));
       jComboBox_situacao_pesquisa.setFont(fh.getLatoRegular(15f));
       
       
       
       jLabel_titulo_adocoes.setFont(fh.getLatoRegular(18f));
       jLabelPesquisaUsuarios.setFont(fh.getLatoRegular(18f));
       jLabel_analiseDados.setFont(fh.getLatoRegular(18f));
       jLabelToTtalDoacoe.setFont(fh.getLatoRegular(18f));
       
       
       txt_total_doacoes.setFont(fh.getLatoRegular(17f));
       txt_pesquisar.setFont(fh.getLatoLight(18f));
    }

    private void configurar_icones() {
        ImageIcon icon = new ImageIcon("src/icones/Favicon.png");
        
        
        this.setIconImage(icon.getImage());
        
     
        
    }
    
    
    
}
